### ISSUE TITLE
SCC algorithms panic on MatrixGraph if nodes have been removed

### ISSUE THREAD

**Issue by Palladinium** [petgraph/petgraph#523]
### Test Case

```rust
use petgraph::matrix_graph::MatrixGraph;

fn main() {
    let mut graph: MatrixGraph<(), ()> = MatrixGraph::new();

    let a = graph.add_node(());
    let b = graph.add_node(());
    let c = graph.add_node(());

    // Replacing this with remove_node(c) prevents the panics
    graph.remove_node(b);

    // This will panic
    petgraph::algo::tarjan_scc(&graph);
    
    // This will also panic
    // petgraph::algo::kosaraju_scc(&graph);
}
```

### Steps To Reproduce

Run the code above. Run again replacing `tarjan_scc` with `kosaraju_scc`.

### Actual Results

When using `tarjan_scc`:
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.6.2/src/algo/mod.rs:401:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/core/src/panicking.rs:65:14
   2: core::panicking::panic_bounds_check
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/core/src/panicking.rs:150:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/core/src/slice/index.rs:259:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/alloc/src/vec/mod.rs:2726:9
   6: petgraph::algo::TarjanScc<N>::run
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.6.2/src/algo/mod.rs:401:27
   7: petgraph::algo::tarjan_scc
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.6.2/src/algo/mod.rs:513:9
   8: petgraph_bug::main
             at ./src/main.rs:14:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

When using `kosaraju_scc`:
```
thread 'main' panicked at 'put at index 2 exceeds fixbitset size 2', /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/fixedbitset-0.4.2/src/lib.rs:225:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/core/src/panicking.rs:65:14
   2: fixedbitset::FixedBitSet::put
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/fixedbitset-0.4.2/src/lib.rs:225:9
   3: <fixedbitset::FixedBitSet as petgraph::visit::VisitMap<Ix>>::visit
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.6.2/src/visit/mod.rs:408:10
   4: petgraph::visit::traversal::DfsPostOrder<N,VM>::next
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.6.2/src/visit/traversal.rs:204:16
   5: petgraph::algo::kosaraju_scc
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/petgraph-0.6.2/src/algo/mod.rs:316:30
   6: petgraph_bug::main
             at ./src/main.rs:14:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/c090c6880c0183ba248bde4a16e29ba29ac4fbba/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected Results

The algorithms complete without panicking.

**Comment by insideoutclub** [comment]
https://github.com/petgraph/petgraph/pull/537

**Comment by insideoutclub** [comment]
@ABorgna Is it time to resolve this issue? Thanks!

**Comment by ABorgna** [comment]
Yes, it seems I referenced the wrong issue there
